### PR TITLE
Exporting default checkRole and authenticate functions

### PR DESCRIPTION
**Pull request by tomyitav**
close #20

### CODE REVIEW

**Comment by czystyl** [comment]
That's great, one more thing if you could update readme as well then would be awesome 💪

**Comment by tomyitav** [comment]
Done :)

**Comment by tomyitav** [comment]
Thanks @czystyl, can you please merge it? :-)

**Comment by czystyl** [comment]
@tomyitav You forgot about to check the test and it's failing but I'll fix it ;)

**Comment by tomyitav** [comment]
Hi @czystyl, I have tried to use the new version in my project, and it seams like the typing definitions were not built properly.
I have noticed that your prepublish script, does not execute build:types script. Hence the typescript definitions are missing. Can you change prepublish to "build && build:types" and republish?
Thanks, Tom

**Comment by czystyl** [comment]
Definitely, the CI should be improved.

Types added: `graphql-directive-auth 0.3.1 published 🎉`

Thanks, @tomyitav for your help :)

**Pull request merged**
